// <auto-generated />
using System;
using FiekHealthCareManagment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FiekHealthCareManagment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210705230159_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("FiekHealthCareManagment.Models.Anamnesis", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("MaxTension")
                        .HasColumnType("int");

                    b.Property<int>("MinTension")
                        .HasColumnType("int");

                    b.Property<double>("Pulse")
                        .HasColumnType("double");

                    b.Property<double>("Spo2")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Anamneses");
                });

            modelBuilder.Entity("FiekHealthCareManagment.Models.MedicalReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AnamnesisId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReportName")
                        .HasColumnType("longtext");

                    b.Property<string>("TherapyId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AnamnesisId");

                    b.HasIndex("PatientId");

                    b.HasIndex("TherapyId");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("FiekHealthCareManagment.Models.Medicine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("TherapyId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TherapyId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("FiekHealthCareManagment.Models.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("FiekHealthCareManagment.Models.Therapy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InsertedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Therapies");
                });

            modelBuilder.Entity("FiekHealthCareManagment.Models.MedicalReport", b =>
                {
                    b.HasOne("FiekHealthCareManagment.Models.Anamnesis", "Anamnesis")
                        .WithMany()
                        .HasForeignKey("AnamnesisId");

                    b.HasOne("FiekHealthCareManagment.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.HasOne("FiekHealthCareManagment.Models.Therapy", "Therapy")
                        .WithMany()
                        .HasForeignKey("TherapyId");

                    b.Navigation("Anamnesis");

                    b.Navigation("Patient");

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("FiekHealthCareManagment.Models.Medicine", b =>
                {
                    b.HasOne("FiekHealthCareManagment.Models.Therapy", null)
                        .WithMany("Medicine")
                        .HasForeignKey("TherapyId");
                });

            modelBuilder.Entity("FiekHealthCareManagment.Models.Therapy", b =>
                {
                    b.HasOne("FiekHealthCareManagment.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FiekHealthCareManagment.Models.Therapy", b =>
                {
                    b.Navigation("Medicine");
                });
#pragma warning restore 612, 618
        }
    }
}
